# updated workflow

name: H1B Visa Slot Checker

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  check-slots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt
          pip install -U selenium seleniumbase

      - name: Verify installations
        run: |
          python --version
          google-chrome --version
          pip list

      - name: Run checker
        run: |
          python -u visa_slot_checker.py
